### ISSUE TITLE
Travis-CI support

### ISSUE THREAD

**Issue by MoOx** [tschaub/gh-pages#22]
I tried to use this module to autodeploy from Travis-CI.
From the build log it seems to work https://travis-ci.org/MoOx/statinamic/builds/81526747#L639-L647
but it doesn't push anything.
FYI, I configured a GH_TOKEN value, I guess you are not using it, but why is the log saying it's working?
Are you open to a PR to handle this?

**Comment by marco-c** [comment]
See https://github.com/mozilla/oghliner which allows you to easily configure auto-deploy from Travis-CI.

**Comment by tschaub** [comment]
@MoOx a PR adding `GH_TOKEN` support would be great.

It looks like there is also an issue with these silent failures.  I'll try to find some time to dig into it.

**Comment by vvo** [comment]
Yep I also get silent failures, rm -rf node_modules seems to work but that would be awesome to know why its failing

**Comment by benoitvallon** [comment]
@tschaub @MoOx merging the #23 would allow us to do things like: `gh-pages --repo https://$GH_TOKEN@github.com/user/private-repo.git -d dist` which would be a way of launching deployments from Travis.

**Comment by tschaub** [comment]
I'll call this fixed with #23.  Please reopen if this is not enough.

**Comment by MoOx** [comment]
Working for me with the --repo. Thanks!

**Comment by ismay** [comment]
@tschaub The suggested fix does not seem to be working for me with Travis. The error I get is:

```
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
```
[build log here](https://travis-ci.org/ismay/ismay.github.io/builds/114892227#L1753)

It's running this task:
```
"deploy": "gh-pages --repo https://$GH_TOKEN@github.com/ismay/ismay.github.io.git -d build -b master",
```
[see package.json](https://github.com/ismay/ismay.github.io/blob/development/package.json#L9)

The GH_TOKEN should be working correctly as it worked fine with another deploy task. I'd set the user from the command line but did not find a command to do so with `gh-pages --help`. Since this seems to have worked for others, any idea what's going wrong?

**Comment by MoOx** [comment]
@ismay did you try to do what is asked? Example https://github.com/MoOx/statinamic/blob/c2ad13a7e459aaadf3138be3717ca5394c57/docs/scripts/deploy.sh#L3-L7

Some modules does this with random email/name.

**Comment by ismay** [comment]
@MoOx I did, in fact that's how I [used to do it](https://github.com/ismay/ismay.github.io/blob/f651c09ba957f40a0c9d309b935ad2e9be384a98/deploy.sh). But I thought that there might be a gh-pages specific way to deal with this, since there wasn't any mention of setting these values manually in this issue.

**Comment by cdaringe** [comment]
it would be nice if this would stub those `git` user values on our behalf!

**Comment by nickmccurdy** [comment]
You could also use Travis' built in GitHub Pages deployment support, and only use `gh-pages` for manual deployments.
