### ISSUE TITLE
documentation for use with Travis CI

### ISSUE THREAD

**Issue by spences10** [tschaub/gh-pages#226]
Hi thanks for `gh-pages` we use it to deploy [our site] via our individual machines once we merge `development` into `master`

I was hoping I could use `gh-pages` with Travis CI but I haven't managed to get anything running so far so I thought I ask:

As I mentioned we use `gh-pages` via an `npm` script with:

```json
"deploy": "gatsby build --prefix-paths && gh-pages -d public",
```

Travis CI fails with an authentication error, so I created a GitHub token with the repo scope and added that to the Travis settings and then have the `.yml` script to call:

```json
"deploy:travis":
  "gatsby build --prefix-paths && https://$GITHUB_TOKEN@github.com/chingu-voyage3/grad.then.git -d public"
```

The `.travis.yml` calls the `deploy:travis` script:

```yml
after_script: 
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy:travis; fi 
```

Travis CI has the following:

```sh
sh: 1: https://[secure]@github.com/chingu-voyage3/grad.then.git: not found
```

Is there anything I'm missing here?

[our site] https://github.com/chingu-voyage3/grad.then/projects

**Comment by mfrachet** [comment]
Any update on this one ?

**Comment by spences10** [comment]
Forgot I logged this @mfrachet 🙃 

We used a manual process in the end

**Comment by jeremenichelli** [comment]
A couple of recommendations here 🙂

Instead of hard checking the branch, use the Travis deploy action:

```sh
deploy:
  provider: script
  script: npm run deploy:travis
  skip_cleanup: true
  on:
    branch: master
```

If you are creating manual processes, check GH_TOKEN permissions in Travis, and use the form url of:

```
git push --force https://${GH_TOKEN}@github.com/owner/repository.git HEAD:branch_destination
```

Specially in private repositories were Git is going to return a not found even on tokens with push permission.

About the documentation, I don't know how much belongs here since the package just takes the output folder you want and force pushes to `gh-pages` branch.

Anyways, hope this helped.

**Comment by spences10** [comment]
Stale, closing
