### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by ardieorden** [tschaub/gh-pages#354]
I'm currently getting this error when I try to use gh-pages:

```
The "path" argument must be of type string. Received type undefined
```

There's a previous issue that's similar to this (#308) and I saw that it was already fixed in the latest versions. I'm currently using gh-pages@2.2.0. My node version is v12.7.0 and my npm version is 6.10.0.

**Comment by ardieorden** [comment]
Is anyone else getting the same error?

**Comment by yashrajb** [comment]
yes i am getting this error

**Comment by marzer** [comment]
I was getting this error after the 3.1.0 update. Rolled back to 3.0.0 and everything worked OK.

**Comment by brendantang** [comment]
I was also getting this error and realized it happened when I either ran `gh-pages` without any options, or tried to pass an option and forgot the flag (as in `gh-pages my-directory` instead of `gh-pages -d my-directory`).

A more descriptive error would be helpful, but for now maybe try triple-checking for typos if you're still getting this error?

**Comment by webmaster128** [comment]
I get the error when executing `npx gh-pages --message "Update docs [skip ci]" --dist cosmjs/docs_deployment --user "CI deployment <ci@cosmwasm.com>" --repo "git@github.com:CosmWasm/cosmjs.git"` outside of a repo. Running the same command in the repo works. Downgrading to 3.0.0 resolves the problem here.

**Comment by brpaz** [comment]
I am getting the same error.
I dived into the code and I think I found the issue.

It´s on index.js:116.

```
  const clone = path.join(getCacheDir(), filenamify(repo));
```

The `getCacheDir` returns undefined in my case. Diving deeper, I found out it uses the `find-cache-dir` package, which has the following comment on the code:

```
Finds the cache directory using the supplied options.
 * The algorithm tries to find a `package.json` file, searching every parent directory of the `cwd` specified
 * (or implied from other options). It returns a `string` containing the absolute path to the cache directory,
 * or `undefined` if `package.json` was never found or if the `node_modules` directory is unwritable.
```

I don't have a package.json file in my project. that´s why I think I am getting undefined.

**Comment by chucklam** [comment]
I have the [same problem/finding](https://github.com/tschaub/gh-pages/issues/354#issuecomment-674552919) as @brpaz above. My static page is not in a nodejs repo, so there's no package.json or node_modules for `find-cache-dir` to get.

Looks like the [change to use `find-cache-dir`](https://github.com/tschaub/gh-pages/pull/362) was simply to move the cache directory out of the way of yarn2. If the need is just for a temporary directory, then [`tmp`](https://www.npmjs.com/package/tmp) may be more appropriate than `find-cache-dir`.

**Comment by mahidul-islam** [comment]
Still getting the same issue any idea why??

**Comment by tnobile** [comment]
node ./node_modules/gh-pages/bin/gh-pages.js -d build
works

**Comment by sappelhoff** [comment]
reading the [release notes for 3.1.0](https://github.com/tschaub/gh-pages/blob/main/changelog.md#v310)

> The cache directory used by gh-pages is now node_modules/.cache/gh-pages. If you want to use a different location, set the CACHE_DIR environment variable.

perhaps this issue can be solved by making a new (temporary) dir and passing it to a `CACHE_DIR` env variable.

**Comment by evaera** [comment]
Still getting this error! Trying to publish without a package.json breaks it.

**Comment by 1j01** [comment]
Adding `--dist .` [fixed the error for me.](https://github.com/1j01/guitar/commit/0fbd1bd6b3bee0c6252ee577a5ff80091dc1e484)

----------------

I was getting this error with gh-pages 5.0.0, whether running via npm script, `npx`, or `node ./node_modules/gh-pages/bin/gh-pages.js`, with or without arguments, with `package.json` present:
```bash
npx gh-pages --src "{index.html,built,lib,tabs,impulses}/**/*"
gh-pages --src "{index.html,built,lib,tabs,impulses}"
gh-pages
node ./node_modules/gh-pages/bin/gh-pages.js --src "{index.html,built,lib,tabs,impulses}"
mkdir -p .gh-pages-cache && CACHE_DIR=.gh-pages-cache gh-pages --src "{index.html,built,lib,tabs,impulses}"
mkdir -p .gh-pages-cache && CACHE_DIR=$(realpath .gh-pages-cache) gh-pages --src "{index.html,built,lib,tabs,impulses}"
```
Debugging this with VS Code launch.json...
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Debug gh-pages",
			"skipFiles": [
				"<node_internals>/**"
			],
			"program": "./node_modules/gh-pages/bin/gh-pages.js",
			"outFiles": [
				"${workspaceFolder}/**/*.js"
			]
		}
	]
}
```
I found that was [failing here](https://github.com/tschaub/gh-pages/blob/2b21f2a6dfad3d6ca807cf0f93f06123ce9e2d67/bin/gh-pages.js#L11):
```
function publish(config) {
  return new Promise((resolve, reject) => {
    const basePath = path.resolve(process.cwd(), program.dist);
```
`program.dist` is `undefined`

By the way, this sort of error would be easier to track down if it logged the `err.stack` instead of [`err.message` here](https://github.com/tschaub/gh-pages/blob/2b21f2a6dfad3d6ca807cf0f93f06123ce9e2d67/bin/gh-pages.js#L138). If there are other errors where only the message is desired, treat them as a special case.

**Comment by domsleee** [comment]
I also had this problem (even with a `package.json`) and it worked after I used the `--dist` option (same as https://github.com/tschaub/gh-pages/issues/354#issuecomment-1501007663)

This is the current behaviour for this (invalid) command:
```bash
❯ npx gh-pages dist
The "path" argument must be of type string. Received undefined
```

Is `--dist` a mandatory option? If so, I would suggest an error message like this:
```bash
❯ npx gh-pages dist
No base directory specified. The `--dist` option must be specified.
```

For clarity, the correct command in my case is `npx gh-pages --dist dist`.

Let me know if there is interest in a PR, I can add this error message and a scenario in [gh-pages.spec.js](https://github.com/tschaub/gh-pages/blob/main/test/bin/gh-pages.spec.js) 👍

**Comment by marzer** [comment]
@tschaub mind giving this issue some attention? It's still affecting people three years on.

**Comment by userlerueda** [comment]
What solved it for us was just running a `touch package.json` prior to executing `gh-pages` in our CI/CD pipeline, not an elegant solution but it did work for us.
