### ISSUE TITLE
cli --no-push not working?

### ISSUE THREAD

**Issue by tleunen** [tschaub/gh-pages#56]
It seems the `--no-push` option with the CLI doesn't work properly. Based on my tests, the commit is still pushed on origin.

**Comment by rschamp** [comment]
Oof, this just bit me.  I don't think this option has ever worked. #46 which added it was submitted with the option called `commit-only`, but it was changed to `no-push` in review.  It was probably not tested with the new name, which doesn't work as expected because of the way `commander` treats `no-` prefixed options.

@tschaub If someone fixes the conflicts, would you consider merging the fix in #71 soon?

**Comment by tschaub** [comment]
Yes.  A conflict free version of #71 would be great.

**Comment by rschamp** [comment]
Thanks @tschaub — see #137.  And thanks for gh-pages, it's super useful!

**Comment by soykje** [comment]
Hi, it seems that the PR could not have been implemented, due to conflicts in package.json (?) :cry:

**Comment by rschamp** [comment]
@soykje Conflicts resolved, but in the meantime the lint rules changed, so will need to fix that.
